import { pgTable, uuid, varchar, boolean, integer, jsonb, timestamp } from 'drizzle-orm/pg-core';
import { orgs } from './orgs';

export const attendancePolicies = pgTable('attendance_policies', {
  id: uuid('id').defaultRandom().primaryKey(),
  orgId: uuid('org_id').notNull().references(() => orgs.id, { onDelete: 'cascade' }),
  name: varchar('name', { length: 255 }).notNull().default('Default Policy'),
  trackingMethods: jsonb('tracking_methods').default(['web']),
  graceMinutesLate: integer('grace_minutes_late').notNull().default(15),
  graceMinutesEarly: integer('grace_minutes_early').notNull().default(15),
  halfDayThresholdMinutes: integer('half_day_threshold_minutes').notNull().default(240),
  fullDayThresholdMinutes: integer('full_day_threshold_minutes').notNull().default(480),
  lateMarkRules: jsonb('late_mark_rules').default({}),
  overtimeEnabled: boolean('overtime_enabled').notNull().default(false),
  overtimeRates: jsonb('overtime_rates').default({}),
  maxOvertimePerDay: integer('max_overtime_per_day').default(4),
  maxOvertimePerWeek: integer('max_overtime_per_week').default(20),
  maxOvertimePerMonth: integer('max_overtime_per_month').default(60),
  overtimeApprovalType: varchar('overtime_approval_type', { length: 30 }).default('pre_approval'),
  compOffConversionRules: jsonb('comp_off_conversion_rules').default({}),
  regularizationDeadlineDays: integer('regularization_deadline_days').default(7),
  regularizationApprovalRequired: boolean('regularization_approval_required').notNull().default(true),
  autoClockOut: boolean('auto_clock_out').notNull().default(true),
  autoClockOutTime: varchar('auto_clock_out_time', { length: 10 }).default('21:00'),
  geoFenceEnabled: boolean('geo_fence_enabled').notNull().default(false),
  wifiValidationEnabled: boolean('wifi_validation_enabled').notNull().default(false),
  allowedWifiNetworks: jsonb('allowed_wifi_networks').default([]),
  payrollCutoffDay: integer('payroll_cutoff_day').default(25),
  lockAfterPayroll: boolean('lock_after_payroll').notNull().default(true),
  isDefault: boolean('is_default').notNull().default(true),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});
