import { pgTable, uuid, varchar, integer, numeric, boolean, jsonb, timestamp } from 'drizzle-orm/pg-core';
import { orgs } from './orgs';

export const timesheetPolicies = pgTable('timesheet_policies', {
  id: uuid('id').defaultRandom().primaryKey(),
  orgId: uuid('org_id').notNull().references(() => orgs.id, { onDelete: 'cascade' }),
  name: varchar('name', { length: 255 }).default('Default Timesheet Policy'),
  submissionFrequency: varchar('submission_frequency', { length: 30 }).notNull().default('weekly'),
  submissionDeadline: varchar('submission_deadline', { length: 30 }).notNull().default('end_of_week'),
  customDeadlineDay: integer('custom_deadline_day'),
  customDeadlineTime: varchar('custom_deadline_time', { length: 10 }),
  minHoursPerDay: numeric('min_hours_per_day', { precision: 4, scale: 1 }).default('8'),
  maxHoursPerDay: numeric('max_hours_per_day', { precision: 4, scale: 1 }).default('12'),
  minHoursPerWeek: numeric('min_hours_per_week', { precision: 5, scale: 1 }).default('40'),
  maxHoursPerWeek: numeric('max_hours_per_week', { precision: 5, scale: 1 }).default('60'),
  roundingRule: varchar('rounding_rule', { length: 30 }).default('none'),
  roundingInterval: integer('rounding_interval').default(15),
  lockAfterApproval: boolean('lock_after_approval').notNull().default(true),
  lockAfterDays: integer('lock_after_days'),
  gracePeriodDays: integer('grace_period_days').default(2),
  dailyMandatory: boolean('daily_mandatory').notNull().default(false),
  requireDescription: boolean('require_description').notNull().default(false),
  autoApprovalEnabled: boolean('auto_approval_enabled').notNull().default(false),
  autoApprovalRules: jsonb('auto_approval_rules').default([]),
  escalationEnabled: boolean('escalation_enabled').notNull().default(false),
  escalationHours: integer('escalation_hours'),
  approvalLevels: jsonb('approval_levels').default([]),
  delegationRules: jsonb('delegation_rules').default({}),
  metadata: jsonb('metadata').default({}),
  isDefault: boolean('is_default').notNull().default(true),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});
